// Account
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Account = Source{[Schema="dbo",Item="Account"]}[Data],
    #"Duplicate Policy Number" = Table.DuplicateColumn(dbo_Account, "POLICY_NUMBER", "POLICY_NUMBER - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicate Policy Number", "CLIENT_CODE", "CLIENT_CODE - Copy"),
    #"Merged Unique Key" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"POLICY_NUMBER - Copy", type text}, {"CLIENT_CODE - Copy", type text}}, "en-MY"),{"POLICY_NUMBER - Copy", "CLIENT_CODE - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Policy Client Code"),
    #"Renamed Columns" = Table.RenameColumns(#"Merged Unique Key",{{"TYPE", "Insurance Product"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"UK - Policy Client Code", Int64.Type}}),
    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"POLICY_STATUS", Text.Trim, type text}}),
    Custom1 = Table.AddColumn(#"Trimmed Text", "MaxDate", each List.Max(#"Trimmed Text"[ISSUE_DATE]) - [ISSUE_DATE]),
    #"Changed Type" = Table.TransformColumnTypes(Custom1,{{"MaxDate", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"MaxDate", "Policy Term (Days)"}, {"MODAL_PREMIUM", "Modal Premium"}, {"ISSUE_DATE", "Date Issued"}, {"PLAN_CODE", "Plan Code"}, {"POLICY_STATUS", "Policy Status"}, {"PAYMENT_MODE", "Payment Mode"}, {"POLICY_NUMBER", "Policy Number"}, {"SURRENDER_DATE", "Surrender Date"}, {"SUM_ASSURED", "Sum Assured"}, {"CLIENT_CODE", "Client Code"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"Policy Number", "Sum Assured", "Modal Premium", "Date Issued", "Surrender Date", "Payment Mode", "Policy Term (Days)"}),
    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "Total Premiums Charged", each [Modal Premium] * [Payment Mode]),
    #"Added Conditional Column" = Table.AddColumn(#"Added Custom", "Custom", each if [Payment Mode] >= 1 then [Total Premiums Charged] else if [Payment Mode] = 0 then [Modal Premium] else null),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Custom", Int64.Type}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type3",{{"Total Premiums Charged", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type2",{"Total Premiums Charged"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"Custom", "Total Premiums Charged"}}),
    #"Sorted Rows" = Table.Sort(#"Renamed Columns2",{{"Policy Number", Order.Ascending}})
in
    #"Sorted Rows"

let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Customer = Source{[Schema="dbo",Item="Customer"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(dbo_Customer,{{"AGE", "Age"}, {"CLIENT_CODE", "Client Code"}, {"MARITAL_STATUS", "Marital Status"}}),
    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Age", each "Age Group " & _, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Added Prefix","M","Male",Replacer.ReplaceText,{"GENDER"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"GENDER"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value1",{{"INCOME", "Income"}, {"GENDER", "Gender"}, {"LASTUPDATE", "Latest Update"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"POSTCODE"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"Latest Update", Order.Ascending}}),
    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
    #"Duplicated Column" = Table.DuplicateColumn(#"Added Index", "Client Code", "Client Code - Copy"),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column", {{"Index", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Index", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"SK - Auto Client Code"),
    #"PaddedClientCode" = Table.TransformColumns(#"Merged Columns", {{"SK - Auto Client Code", each Text.PadEnd(Text.From(_), 9, "0"), type  text}}),
    #"Duplicated Column1" = Table.DuplicateColumn(PaddedClientCode, "Client Code", "Client Code - Copy"),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "Latest Update", "Latest Update - Copy"),
    #"Converted Julian Date" = Table.TransformColumns(#"Duplicated Column2", {{"Latest Update - Copy", each 
        let 
            Year = Date.Year(_),
            DayOfYear = Date.DayOfYear(_)
            in
                Text.From(Year - 1900) & Text.PadStart(Text.From(DayOfYear), 3, "0"),
        type text}
    }),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted Julian Date",{{"Latest Update - Copy", Int64.Type}}),
    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Changed Type", {{"Latest Update - Copy", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Latest Update - Copy", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Client Code History"),
    #"PaddedClientCode1" = Table.TransformColumns(#"Merged Columns1", {{"UK - Client Code History", each Text.PadEnd(Text.From(_), 12, "0"), type  text}}),
    #"Removed Other Columns" = Table.SelectColumns(PaddedClientCode1,{"Client Code", "Income", "Latest Update", "SK - Auto Client Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"Client Code", "SK - Auto Client Code", "Income", "Latest Update"})
in
    #"Reordered Columns"