// Account Policy Number
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Account = Source{[Schema="dbo",Item="Account"]}[Data],
    #"Duplicate Policy Number" = Table.DuplicateColumn(dbo_Account, "POLICY_NUMBER", "POLICY_NUMBER - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicate Policy Number", "CLIENT_CODE", "CLIENT_CODE - Copy"),
    #"Merged Unique Key" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"POLICY_NUMBER - Copy", type text}, {"CLIENT_CODE - Copy", type text}}, "en-MY"),{"POLICY_NUMBER - Copy", "CLIENT_CODE - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Policy Client Code"),
    #"Renamed Columns" = Table.RenameColumns(#"Merged Unique Key",{{"TYPE", "Insurance Product"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"UK - Policy Client Code", Int64.Type}}),
    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"POLICY_STATUS", Text.Trim, type text}}),
    Custom1 = Table.AddColumn(#"Trimmed Text", "MaxDate", each List.Max(#"Trimmed Text"[ISSUE_DATE]) - [ISSUE_DATE]),
    #"Changed Type" = Table.TransformColumnTypes(Custom1,{{"MaxDate", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"MaxDate", "Policy Term (Days)"}, {"MODAL_PREMIUM", "Modal Premium"}, {"ISSUE_DATE", "Date Issued"}, {"PLAN_CODE", "Plan Code"}, {"POLICY_STATUS", "Policy Status"}, {"PAYMENT_MODE", "Payment Mode"}, {"POLICY_NUMBER", "Policy Number"}, {"SURRENDER_DATE", "Surrender Date"}, {"SUM_ASSURED", "Sum Assured"}, {"CLIENT_CODE", "Client Code"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"Policy Number", "Client Code", "UK - Policy Client Code"}),
    #"Sorted Rows" = Table.Sort(#"Removed Other Columns",{{"UK - Policy Client Code", Order.Ascending}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Sorted Rows",{"UK - Policy Client Code", "Policy Number", "Client Code"})
in
    #"Reordered Columns"

// Account Plan Code
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Account = Source{[Schema="dbo",Item="Account"]}[Data],
    #"Duplicate Policy Number" = Table.DuplicateColumn(dbo_Account, "POLICY_NUMBER", "POLICY_NUMBER - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicate Policy Number", "CLIENT_CODE", "CLIENT_CODE - Copy"),
    #"Merged Unique Key" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"POLICY_NUMBER - Copy", type text}, {"CLIENT_CODE - Copy", type text}}, "en-MY"),{"POLICY_NUMBER - Copy", "CLIENT_CODE - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Policy Client Code"),
    #"Renamed Columns" = Table.RenameColumns(#"Merged Unique Key",{{"TYPE", "Insurance Product"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"UK - Policy Client Code", Int64.Type}}),
    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"POLICY_STATUS", Text.Trim, type text}}),
    Custom1 = Table.AddColumn(#"Trimmed Text", "MaxDate", each List.Max(#"Trimmed Text"[ISSUE_DATE]) - [ISSUE_DATE]),
    #"Changed Type" = Table.TransformColumnTypes(Custom1,{{"MaxDate", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"MaxDate", "Policy Term (Days)"}, {"MODAL_PREMIUM", "Modal Premium"}, {"ISSUE_DATE", "Date Issued"}, {"PLAN_CODE", "Plan Code"}, {"POLICY_STATUS", "Policy Status"}, {"PAYMENT_MODE", "Payment Mode"}, {"POLICY_NUMBER", "Policy Number"}, {"SURRENDER_DATE", "Surrender Date"}, {"SUM_ASSURED", "Sum Assured"}, {"CLIENT_CODE", "Client Code"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"Plan Code", "Client Code", "UK - Policy Client Code"}),
    #"Sorted Rows" = Table.Sort(#"Removed Other Columns",{{"UK - Policy Client Code", Order.Ascending}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Sorted Rows",{"UK - Policy Client Code", "Plan Code", "Client Code"})
in
    #"Reordered Columns"

// Plan Code Insurance Product
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Account = Source{[Schema="dbo",Item="Account"]}[Data],
    #"Duplicate Policy Number" = Table.DuplicateColumn(dbo_Account, "POLICY_NUMBER", "POLICY_NUMBER - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicate Policy Number", "CLIENT_CODE", "CLIENT_CODE - Copy"),
    #"Merged Unique Key" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"POLICY_NUMBER - Copy", type text}, {"CLIENT_CODE - Copy", type text}}, "en-MY"),{"POLICY_NUMBER - Copy", "CLIENT_CODE - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Policy Client Code"),
    #"Renamed Columns" = Table.RenameColumns(#"Merged Unique Key",{{"TYPE", "Insurance Product"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"UK - Policy Client Code", Int64.Type}}),
    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"POLICY_STATUS", Text.Trim, type text}}),
    Custom1 = Table.AddColumn(#"Trimmed Text", "MaxDate", each List.Max(#"Trimmed Text"[ISSUE_DATE]) - [ISSUE_DATE]),
    #"Changed Type" = Table.TransformColumnTypes(Custom1,{{"MaxDate", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"MaxDate", "Policy Term (Days)"}, {"MODAL_PREMIUM", "Modal Premium"}, {"ISSUE_DATE", "Date Issued"}, {"PLAN_CODE", "Plan Code"}, {"POLICY_STATUS", "Policy Status"}, {"PAYMENT_MODE", "Payment Mode"}, {"POLICY_NUMBER", "Policy Number"}, {"SURRENDER_DATE", "Surrender Date"}, {"SUM_ASSURED", "Sum Assured"}, {"CLIENT_CODE", "Client Code"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"Plan Code", "Insurance Product"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Plan Code"}),
    #"Sorted Rows" = Table.Sort(#"Removed Duplicates",{{"Plan Code", Order.Ascending}})
in
    #"Sorted Rows"

// Client Code Policy Status
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Account = Source{[Schema="dbo",Item="Account"]}[Data],
    #"Duplicate Policy Number" = Table.DuplicateColumn(dbo_Account, "POLICY_NUMBER", "POLICY_NUMBER - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicate Policy Number", "CLIENT_CODE", "CLIENT_CODE - Copy"),
    #"Merged Unique Key" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"POLICY_NUMBER - Copy", type text}, {"CLIENT_CODE - Copy", type text}}, "en-MY"),{"POLICY_NUMBER - Copy", "CLIENT_CODE - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Policy Client Code"),
    #"Renamed Columns" = Table.RenameColumns(#"Merged Unique Key",{{"TYPE", "Insurance Product"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"UK - Policy Client Code", Int64.Type}}),
    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"POLICY_STATUS", Text.Trim, type text}}),
    Custom1 = Table.AddColumn(#"Trimmed Text", "MaxDate", each List.Max(#"Trimmed Text"[ISSUE_DATE]) - [ISSUE_DATE]),
    #"Changed Type" = Table.TransformColumnTypes(Custom1,{{"MaxDate", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"MaxDate", "Policy Term (Days)"}, {"MODAL_PREMIUM", "Modal Premium"}, {"ISSUE_DATE", "Date Issued"}, {"PLAN_CODE", "Plan Code"}, {"POLICY_STATUS", "Policy Status"}, {"PAYMENT_MODE", "Payment Mode"}, {"POLICY_NUMBER", "Policy Number"}, {"SURRENDER_DATE", "Surrender Date"}, {"SUM_ASSURED", "Sum Assured"}, {"CLIENT_CODE", "Client Code"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"Client Code", "Policy Status", "UK - Policy Client Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"UK - Policy Client Code", "Client Code", "Policy Status"}),
    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"UK - Policy Client Code", Order.Ascending}})
in
    #"Sorted Rows"

// Client Code Payment Mode
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Account = Source{[Schema="dbo",Item="Account"]}[Data],
    #"Duplicate Policy Number" = Table.DuplicateColumn(dbo_Account, "POLICY_NUMBER", "POLICY_NUMBER - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicate Policy Number", "CLIENT_CODE", "CLIENT_CODE - Copy"),
    #"Merged Unique Key" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"POLICY_NUMBER - Copy", type text}, {"CLIENT_CODE - Copy", type text}}, "en-MY"),{"POLICY_NUMBER - Copy", "CLIENT_CODE - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Policy Client Code"),
    #"Renamed Columns" = Table.RenameColumns(#"Merged Unique Key",{{"TYPE", "Insurance Product"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"UK - Policy Client Code", Int64.Type}}),
    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"POLICY_STATUS", Text.Trim, type text}}),
    Custom1 = Table.AddColumn(#"Trimmed Text", "MaxDate", each List.Max(#"Trimmed Text"[ISSUE_DATE]) - [ISSUE_DATE]),
    #"Changed Type" = Table.TransformColumnTypes(Custom1,{{"MaxDate", Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type",{{"MaxDate", "Policy Term (Days)"}, {"MODAL_PREMIUM", "Modal Premium"}, {"ISSUE_DATE", "Date Issued"}, {"PLAN_CODE", "Plan Code"}, {"POLICY_STATUS", "Policy Status"}, {"PAYMENT_MODE", "Payment Mode"}, {"POLICY_NUMBER", "Policy Number"}, {"SURRENDER_DATE", "Surrender Date"}, {"SUM_ASSURED", "Sum Assured"}, {"CLIENT_CODE", "Client Code"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns1",{"Client Code", "Payment Mode", "UK - Policy Client Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"UK - Policy Client Code", "Client Code", "Payment Mode"}),
    #"Sorted Rows" = Table.Sort(#"Reordered Columns",{{"UK - Policy Client Code", Order.Ascending}})
in
    #"Sorted Rows"

// Client Code
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Customer = Source{[Schema="dbo",Item="Customer"]}[Data],
    #"Removed Other Columns" = Table.SelectColumns(dbo_Customer,{"CLIENT_CODE"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"CLIENT_CODE", "Client Code"}})
in
    #"Renamed Columns"

// Customer Age
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Customer = Source{[Schema="dbo",Item="Customer"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(dbo_Customer,{{"AGE", "Age"}, {"CLIENT_CODE", "Client Code"}, {"MARITAL_STATUS", "Marital Status"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","M","Male",Replacer.ReplaceText,{"GENDER"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"GENDER"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value1",{{"INCOME", "Income"}, {"GENDER", "Gender"}, {"LASTUPDATE", "Latest Update"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"POSTCODE"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"Latest Update", Order.Ascending}}),
    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
    #"Duplicated Column" = Table.DuplicateColumn(#"Added Index", "Client Code", "Client Code - Copy"),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column", {{"Index", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Index", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"SK - Auto Client Code"),
    #"PaddedClientCode" = Table.TransformColumns(#"Merged Columns", {{"SK - Auto Client Code", each Text.PadEnd(Text.From(_), 9, "0"), type  text}}),
    #"Duplicated Column1" = Table.DuplicateColumn(PaddedClientCode, "Client Code", "Client Code - Copy"),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "Latest Update", "Latest Update - Copy"),
    #"Converted Julian Date" = Table.TransformColumns(#"Duplicated Column2", {{"Latest Update - Copy", each 
        let 
            Year = Date.Year(_),
            DayOfYear = Date.DayOfYear(_)
            in
                Text.From(Year - 1900) & Text.PadStart(Text.From(DayOfYear), 3, "0"),
        type text}
    }),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted Julian Date",{{"Latest Update - Copy", Int64.Type}}),
    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Changed Type", {{"Latest Update - Copy", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Latest Update - Copy", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Client Code History"),
    #"PaddedClientCode1" = Table.TransformColumns(#"Merged Columns1", {{"UK - Client Code History", each Text.PadEnd(Text.From(_), 12, "0"), type  text}}),
    #"Removed Other Columns" = Table.SelectColumns(PaddedClientCode1,{"Age", "SK - Auto Client Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"SK - Auto Client Code", "Age"})
in
    #"Reordered Columns"

// Customer Gender
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Customer = Source{[Schema="dbo",Item="Customer"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(dbo_Customer,{{"AGE", "Age"}, {"CLIENT_CODE", "Client Code"}, {"MARITAL_STATUS", "Marital Status"}}),
    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Age", each "Age Group " & _, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Added Prefix","M","Male",Replacer.ReplaceText,{"GENDER"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"GENDER"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value1",{{"INCOME", "Income"}, {"GENDER", "Gender"}, {"LASTUPDATE", "Latest Update"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"POSTCODE"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"Latest Update", Order.Ascending}}),
    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
    #"Duplicated Column" = Table.DuplicateColumn(#"Added Index", "Client Code", "Client Code - Copy"),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column", {{"Index", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Index", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"SK - Auto Client Code"),
    #"PaddedClientCode" = Table.TransformColumns(#"Merged Columns", {{"SK - Auto Client Code", each Text.PadEnd(Text.From(_), 9, "0"), type  text}}),
    #"Duplicated Column1" = Table.DuplicateColumn(PaddedClientCode, "Client Code", "Client Code - Copy"),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "Latest Update", "Latest Update - Copy"),
    #"Converted Julian Date" = Table.TransformColumns(#"Duplicated Column2", {{"Latest Update - Copy", each 
        let 
            Year = Date.Year(_),
            DayOfYear = Date.DayOfYear(_)
            in
                Text.From(Year - 1900) & Text.PadStart(Text.From(DayOfYear), 3, "0"),
        type text}
    }),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted Julian Date",{{"Latest Update - Copy", Int64.Type}}),
    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Changed Type", {{"Latest Update - Copy", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Latest Update - Copy", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Client Code History"),
    #"PaddedClientCode1" = Table.TransformColumns(#"Merged Columns1", {{"UK - Client Code History", each Text.PadEnd(Text.From(_), 12, "0"), type  text}}),
    #"Removed Other Columns" = Table.SelectColumns(PaddedClientCode1,{"Gender", "SK - Auto Client Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"SK - Auto Client Code", "Gender"})
in
    #"Reordered Columns"

// Customer Marital Status
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Customer = Source{[Schema="dbo",Item="Customer"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(dbo_Customer,{{"AGE", "Age"}, {"CLIENT_CODE", "Client Code"}, {"MARITAL_STATUS", "Marital Status"}}),
    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Age", each "Age Group " & _, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Added Prefix","M","Male",Replacer.ReplaceText,{"GENDER"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"GENDER"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value1",{{"INCOME", "Income"}, {"GENDER", "Gender"}, {"LASTUPDATE", "Latest Update"}}),
    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns1",{"POSTCODE"}),
    #"Sorted Rows" = Table.Sort(#"Removed Columns",{{"Latest Update", Order.Ascending}}),
    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
    #"Duplicated Column" = Table.DuplicateColumn(#"Added Index", "Client Code", "Client Code - Copy"),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column", {{"Index", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Index", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"SK - Auto Client Code"),
    #"PaddedClientCode" = Table.TransformColumns(#"Merged Columns", {{"SK - Auto Client Code", each Text.PadEnd(Text.From(_), 9, "0"), type  text}}),
    #"Duplicated Column1" = Table.DuplicateColumn(PaddedClientCode, "Client Code", "Client Code - Copy"),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "Latest Update", "Latest Update - Copy"),
    #"Converted Julian Date" = Table.TransformColumns(#"Duplicated Column2", {{"Latest Update - Copy", each 
        let 
            Year = Date.Year(_),
            DayOfYear = Date.DayOfYear(_)
            in
                Text.From(Year - 1900) & Text.PadStart(Text.From(DayOfYear), 3, "0"),
        type text}
    }),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted Julian Date",{{"Latest Update - Copy", Int64.Type}}),
    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Changed Type", {{"Latest Update - Copy", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Latest Update - Copy", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Client Code History"),
    #"PaddedClientCode1" = Table.TransformColumns(#"Merged Columns1", {{"UK - Client Code History", each Text.PadEnd(Text.From(_), 12, "0"), type  text}}),
    #"Removed Other Columns" = Table.SelectColumns(PaddedClientCode1,{"Marital Status", "SK - Auto Client Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"SK - Auto Client Code", "Marital Status"})
in
    #"Reordered Columns"

// Customer Post Codes
let
    Source = Sql.Database("DESKTOP-QS5GMB1\SQLEXPRESS", "HBA"),
    dbo_Customer = Source{[Schema="dbo",Item="Customer"]}[Data],
    #"Renamed Columns" = Table.RenameColumns(dbo_Customer,{{"AGE", "Age"}, {"CLIENT_CODE", "Client Code"}, {"MARITAL_STATUS", "Marital Status"}}),
    #"Added Prefix" = Table.TransformColumns(#"Renamed Columns", {{"Age", each "Age Group " & _, type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Added Prefix","M","Male",Replacer.ReplaceText,{"GENDER"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"GENDER"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value1",{{"INCOME", "Income"}, {"GENDER", "Gender"}, {"LASTUPDATE", "Latest Update"}, {"POSTCODE", "Post Code"}}),
    #"Sorted Rows" = Table.Sort(#"Renamed Columns1",{{"Latest Update", Order.Ascending}}),
    #"Added Index" = Table.AddIndexColumn(#"Sorted Rows", "Index", 1, 1, Int64.Type),
    #"Duplicated Column" = Table.DuplicateColumn(#"Added Index", "Client Code", "Client Code - Copy"),
    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column", {{"Index", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Index", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"SK - Auto Client Code"),
    #"PaddedClientCode" = Table.TransformColumns(#"Merged Columns", {{"SK - Auto Client Code", each Text.PadEnd(Text.From(_), 9, "0"), type  text}}),
    #"Duplicated Column1" = Table.DuplicateColumn(PaddedClientCode, "Client Code", "Client Code - Copy"),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "Latest Update", "Latest Update - Copy"),
    #"Converted Julian Date" = Table.TransformColumns(#"Duplicated Column2", {{"Latest Update - Copy", each 
        let 
            Year = Date.Year(_),
            DayOfYear = Date.DayOfYear(_)
            in
                Text.From(Year - 1900) & Text.PadStart(Text.From(DayOfYear), 3, "0"),
        type text}
    }),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted Julian Date",{{"Latest Update - Copy", Int64.Type}}),
    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Changed Type", {{"Latest Update - Copy", type text}, {"Client Code - Copy", type text}}, "en-MY"),{"Latest Update - Copy", "Client Code - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UK - Client Code History"),
    #"PaddedClientCode1" = Table.TransformColumns(#"Merged Columns1", {{"UK - Client Code History", each Text.PadEnd(Text.From(_), 12, "0"), type  text}}),
    #"Removed Other Columns" = Table.SelectColumns(PaddedClientCode1,{"Post Code", "SK - Auto Client Code"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"SK - Auto Client Code", "Post Code"})
in
    #"Reordered Columns"

// Customer States
let
    Source = Json.Document(File.Contents("C:\Users\QS\datascience\HBA Capital\data\raw\postcodes_malaysia.json")),
    #"Converted to Table" = Table.FromRecords({Source}),
    #"Expanded state" = Table.ExpandListColumn(#"Converted to Table", "state"),
    #"Expanded state1" = Table.ExpandRecordColumn(#"Expanded state", "state", {"name", "city"}, {"state.name", "state.city"}),
    #"Expanded state.city" = Table.ExpandListColumn(#"Expanded state1", "state.city"),
    #"Expanded state.city1" = Table.ExpandRecordColumn(#"Expanded state.city", "state.city", {"name", "postcode"}, {"state.city.name", "state.city.postcode"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded state.city1",{{"state.name", type text}, {"state.city.name", type text}, {"state.city.postcode", type any}}),
    #"Expanded state.city.postcode" = Table.ExpandListColumn(#"Changed Type", "state.city.postcode"),
    #"Renamed Columns" = Table.RenameColumns(#"Expanded state.city.postcode",{{"state.name", "State"}, {"state.city.name", "City"}, {"state.city.postcode", "Postcode"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Postcode", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"City"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"Postcode"})
in
    #"Removed Duplicates"